version: 0.0
os: linux
files:
  - source: /
    destination: /root/git/BoonTermAPIWrapper 
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300 
  ValidateService:
    - location: scripts/health_check.sh
